version: 2
# CodeArtificact registry is required but not currently supported.

updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Health-Education-England/internal-admin-backend

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Health-Education-England/internal-admin-backend
      - Health-Education-England/internal-admin-devops
