debug: true
spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  application:
    name: tis-revalidation-recommendation
  jackson:
    serialization.write_dates_as_timestamps: false
    serialization.indent_output: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    ssl.enabled: ${RABBITMQ_USE_SSL:false}
  elasticsearch:
    rest:
      uris: ${ES_URLS:http://localhost:9200}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://${MONGODB_USERNAME:root}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:revalidation}?${MONGODB_PARAMS:authSource=admin&authMechanism=SCRAM-SHA-1&replicaSet=rs0&readPreference=secondaryPreferred}}

server:
  servlet:
    context-path: /revalidation
  port: ${SERVICE_PORT:8080}

logging:
  level:
    uk.nhs.hee.tis.revalidation: ${LOGGING_LEVEL:INFO}
    org.springframework.data.mongodb.core.MongoTemplate: ${LOGGING_LEVEL:ERROR}
    org.springframework.boot.autoconfigure: ${LOGGING_LEVEL:ERROR}

  file:
    name: ${LOG_DIR:${HOME}}/revalidation.log

management:
  endpoints:
    health:
      enabled: true
    web:
      exposure:
        include: '*'
  server:
    servlet:
      context-path: /management

app:
  error:
    exchange: "ex.error"
    limit.retries: true

  reval:
    event.store.db: ${EVENT_STORE:eventstore}
    event.store.collection: ${EVENT_STORE_COLLECTION:events_log}
    pagination.pageSize: ${PAGINATION_PAGE_SIZE:20}
    tcs.url: ${TCS_URL:http:localhost:8080/tcsmock/api/revalidation}

  validation:
    sort.fields: ${SORT_FIELD:submissionDate,doctorFirstName,doctorLastName,gmcReferenceNumber}
    sort.order: ${SORT_ORDER:asc,desc}

  rabbit:
    connection.queue: ${CONNECTION_QUEUE:reval.queue.connection.manualupdate.recommendation}
    reval:
      exchange: ${REVAL_RABBIT_EXCHANGE:reval.exchange}
      queue.recommendation.syncstart: ${REVAL_RABBIT_RECOMMENDATION_SYNC_START_QUEUE:reval.queue.recommendation.syncstart}
      queue.recommendationStatusCheck.updated: ${REVAL_RABBIT_RECOMMENDATION_STATUS_CHECK_UPDATED_QUEUE:reval.queue.recommendationstatuscheck.updated.recommendation}
      routingKey.recommendationstatuscheck.requested: ${REVAL_RABBIT_RECOMMENDATION_STATUS_CHECK_REQUESTED_ROUTING_KEY:reval.recommendationstatuscheck.requested}
      routingKey.gmcsync.requested.gmcclient: ${REVAL_RABBIT_GMCSYNC_REQUESTED_GMCCLIENT_ROUTING_KEY:reval.gmcsync.requested}
      queue.masterdoctorview.updated.recommendation: ${REVAL_RABBIT_UPDATE_RECOMMENDATION_INDEX_VIEW:reval.queue.masterdoctorview.updated.recommendation}
      queue.doctorsfordb.collected.recommendation: ${REVAL_RABBIT_DOCTORS_FOR_DB_COLLECTED_QUEUE:reval.queue.doctorsfordb.collected.recommendation}

  gmc:
    url: ${GMC_CONNECT_URL:http://localhost:8090/GMCConnectMock2020/GMCWebServices}
    soapActionBase: ${GMC_SOAP_ACTION_BASE:https://webcache.gmc-uk.org/GMCWebServices/}
    gmcUsername: ${GMC_USER_NAME:guest}
    gmcPassword: ${GMC_PASSWORD:guest}
    designatedBodies: ${DESIGNATED_BODY_CODE:1-AIIDHJ,1-AIIDMQ,1-AIIDNQ,1-AIIDMY,1-AIIDQQ,1-AIIDWT,1-AIIDR8,1-AIIDSA,1-AIIDH1,1-AIIDWA,1-AIIDVS,1-AIIDWI,1-AIIDSI}
    recommendationstatuscheck.cronExpression: ${REC_STATUS_CHECK_CRON:0 0 8,12,16 * * *}
    nightlySyncStart.cronExpression: ${REC_NIGHTLY_SYNC_CRON:0 0 0 * * *}

  scheduling:
    lock:
      maxTimedefault: 15m
      minTimedefault: 15s

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:}

cloud:
  aws:
    end-point:
      uri: ${SQS_SYNC_GMC_QUEUE:}

mongock:
  change-logs-scan-package: uk.nhs.hee.tis.revalidation.changelog