version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3.7.5-management
    hostname: app-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - /tmp/data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /

  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - '27017:27017'
    volumes:
      - /tmp/data/mongo:/data/db
#    environment:
#      MONGO_INITDB_DATABASE: eventstore
#      MONGO_INITDB_ROOT_USERNAME: guest
#      MONGO_INITDB_ROOT_PASSWORD: guest

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example