version: '3.2'
services:
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3.7.5-management
    hostname: app-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - /tmp/data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
